### ISSUE TITLE
ActionCable uses NullLogger but raises

### ISSUE THREAD

**Issue by stevegeek** [allmarkedup/lookbook#76]
Version 0.7.2

Using log tags with a tagged logger (`rails_semantic_logger` in this case) attempts to call tagged logger methods of `NullLogger` which raises

```
Rails -- Exception: NoMethodError: undefined method `tags' for #<Lookbook::NullLogger:0x00000001139736f0>

        current_tags = tags - logger.tags
                                    ^^^^^
/Users/stephen/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rails_semantic_logger-4.10.0/lib/rails_semantic_logger/extensions/action_cable/tagged_logger_proxy.rb:7:in `tag'
/Users/stephen/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/actioncable-7.0.2.3/lib/action_cable/connection/tagged_logger_proxy.rb:38:in `log'
/Users/stephen/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/actioncable-7.0.2.3/lib/action_cable/connection/tagged_logger_proxy.rb:32:in `block (2 levels) in <class:TaggedLoggerProxy>'
/Users/stephen/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/actioncable-7.0.2.3/lib/action_cable/connection/base.rb:72:in `process'
/Users/stephen/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/actioncable-7.0.2.3/lib/action_cable/server/base.rb:33:in `call'
/Users/stephen/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
/Users/stephen/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:48:in `serve'
/Users/stephen/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/Users/stephen/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/journey/router.rb:32:in `each'
/Users/stephen/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/journey/router.rb:32:in `serve'
/Users/stephen/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/route_set.rb:850:in `call'
/Users/stephen/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/engine.rb:530:in `call'
/Users/stephen/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/railtie.rb:224:in `public_send'
/Users/stephen/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/railtie.rb:224:in `method_missing'
/Users/stephen/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
/Users/stephen/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:48:in `serve'
/Users/stephen/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/Users/stephen/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/journey/router.rb:32:in `each'
/Users/stephen/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/journey/router.rb:32:in `serve'
/Users/stephen/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/route_set.rb:850:in `call'
/Users/stephen/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/static.rb:23:in `call'
```

**Comment by allmarkedup** [comment]
@stevegeek I've just released v0.7.3 that should fix this issue. Any problems with it just let me know.

**Comment by stevegeek** [comment]
@allmarkedup thanks so much!

**Comment by raivil** [comment]
Hey @allmarkedup,
First of all, thank you for creating this gem.

I'm facing a similar issue with logs when using lookbook `1.0.8`. 
My app is using rails_semantic_logger (4.10.0) and outputs to stdout on development.

I've found that lookbook will use `Logger.new($stdout)` when in development mode.  
https://github.com/allmarkedup/lookbook/blob/1bb5fc843c7c25278309b838f0df89d4d1e8cda8/lib/lookbook/engine.rb#L30-L32


What is the reasoning behind that? Shouldn't lookbook use the development configured logger?

Best,


```
web    | 2022-09-16 09:00:01.099865 F [86518:puma srv tp 001 abstract_thread_local_var.rb:43] Rails -- Exception: NoMethodError: undefined method `tags' for #<Logger:0x000000010fa13190 @level=2, @progname=nil, @default_formatter=#<Logger::Formatter:0x000000010fa130f0 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x000000010fa13050 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @binmode=false, @mon_data=#<Monitor:0x000000010fa13000>, @mon_data_owner_object_id=9520>>
web    | 
web    |         current_tags = tags - logger.tags
web    |                                     ^^^^^
web    | /Users/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rails_semantic_logger-4.10.0/lib/rails_semantic_logger/extensions/action_cable/tagged_logger_proxy.rb:7:in `tag'
web    | /Users/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actioncable-7.0.4/lib/action_cable/connection/tagged_logger_proxy.rb:38:in `log'
web    | /Users/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actioncable-7.0.4/lib/action_cable/connection/tagged_logger_proxy.rb:32:in `block (2 levels) in <class:TaggedLoggerProxy>'
web    | /Users/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actioncable-7.0.4/lib/action_cable/connection/base.rb:72:in `process'
web    | /Users/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actioncable-7.0.4/lib/action_cable/server/base.rb:33:in `call'
web    | /Users/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
web    | /Users/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/routing/mapper.rb:48:in `serve'
web    | /Users/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb:50:in `block in serve'
web    | /Users/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb:32:in `each'
web    | /Users/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb:32:in `serve'
web    | /Users/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/routing/route_set.rb:852:in `call'
web    | /Users/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/engine.rb:530:in `call'
web    | /Users/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/railtie.rb:226:in `public_send'
web    | /Users/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/railtie.rb:226:in `method_missing'
web    | /Users/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
web    | /Users/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/routing/mapper.rb:48:in `serve'
web    | /Users/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb:50:in `block in serve'
web    | /Users/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb:32:in `each'
web    | /Users/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb:32:in `serve'
web    | /Users/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/routing/route_set.rb:852:in `call'
web    | /Users/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/static.rb:23:in `call'
```

**Comment by allmarkedup** [comment]
Hey @raivil - if I'm honest I can't remember the reasoning behind that! In fact I was looking at it the other day and thinking that it should just use whatever is configured as the logger in the parent Rails app.

I'll make that change when I get a chance and include it in the next release. Thanks for highlighting the issue :-)

**Comment by jukrieger** [comment]
@allmarkedup I'm still facing this problem in 2024 when using Semantic Logger in cooperation with Lookbook. Any pointers where I could look into it? I would be willing to open a PR.
