### ISSUE TITLE
Test and support a a wide range of possible ViewComponent project setups and structures

### ISSUE THREAD

**Issue by allmarkedup** [allmarkedup/lookbook#8]
Right now Lookbook has only been tested with very 'vanilla' ViewComponent/Rails setups. It needs testing and patching to support the widest possible (sensible) range of different project structures/setups.

**Comment by adrienpoly** [comment]
Ok I tested again trying to get as close as possible to a vanilla version but still cannot get the component to display.

- removed the custom preview route
- updated to the latest version of the Gem
- tried removing all style sheets/ JS etc
- No particular error in the browser console
- No errors in the rails console
- Code, output will display fine 
- when I click the box icon with arrow another window opens **with the correct display of the component**
- the size of the component to display is 0px/0px

![Capture d’écran 2021-09-06 à 4 57 49 PM](https://user-images.githubusercontent.com/7847244/132236843-c66d14a1-e4d2-40ad-ba9a-df54be47c8eb.jpg)

Let me know if there is anything more I could look into to help with the debug

**Comment by allmarkedup** [comment]
@adrienpoly thank you that is very helpful!

So the only difference between the preview window and the preview that is displayed when you click on the box/arrow icon is that the former is rendered in an iframe using a `srcdoc` attribute whereas the latter is just rendered in the page. So based on what you are seeing I suspect that there is an issue with the html encoding of the preview that is causing the `srcdoc` attribute to choke.

I've just pushed up a branch with the `srcdoc` removed from the preview: https://github.com/allmarkedup/lookbook/tree/remove-preview-srcdoc which you should be able to use in your Gemfile using: `gem 'lookbook', git: 'https://github.com/allmarkedup/lookbook', branch: 'remove-preview-srcdoc'`

I realise this is probably taking up a lot of your time but if you have a chance to confirm if that solves the issue it would be much appreciated.

**Comment by adrienpoly** [comment]
Hello Thanks for your prompt answer. 

It does indeed solve the issue 🎉 
Is there anything specific on my side that would be causing this ?

Also in the mean time I tried to set back the custom preview route that I had (the initial suspect) and it works too.

**Comment by allmarkedup** [comment]
Excellent! At least we know what the issue is now. And good to know the custom route still works.

It's hard to know what is causing it however - to work as a string in the `srcdoc` attribute, the rendered HTML needs to have all its double quote marks encoded to `&quot;`, otherwise the quotation mark would appear to 'end' the attribute value. That should all be handled by Lookbook... but it seems that there is still some encoding issue going on that has been missed.

Are you able to post up the source HTML for the rendered component preview? Including the `<head>` etc? The best place to copy it from would be the source of the 'new window' preview. If you are happy to share it then I can test it myself and see if I can replicate the problem.

**Comment by adrienpoly** [comment]
Another piece of information while testing #42, I am pretty sure that 0.23 does not includes this patch BUT in staging 0.23 does work for me (but still fails to display the component in development). I will look into providing a full html extract

**Comment by adrienpoly** [comment]
Ok looking into the differences between Staging and development I could identify the conflict. I am using Rack LiveReload in development and when I comment this line it works perfectly.
```ruby
# config/environments/development.rb
# ....
config.middleware.insert_after ActionDispatch::Static, Rack::LiveReload
```

**Comment by allmarkedup** [comment]
Hey @adrienpoly, sorry for the slow reply, but good work on tracking down the culprit.

I'm not quite sure yet why exactly it's causing the iframe to choke, but as an interim fix I've just released v0.2.4 that adds the option to disable use of the `srcdoc` attribute for anyone running into similar issues.

Obviously making sure the escaping works correctly even for injected content would be a better fix and one that I'll still try to look into. But as the `srcdoc` can be a bit fragile, having an option for people to disable it is not a bad thing to have anyway, I think.

Thanks again for all your help with this 👍

**Comment by DRBragg** [comment]
Hey @allmarkedup thanks for all your work on this.  Lookbook is awesome and hopefully I can find some ways to contribute.

RE: this issue, I'm currently working on getting VC and Lookbook adopted at my company so I hope to get you feedback from that.  Lookbook is actually a pretty bit selling point for the adoption. 

Our app is 13 years old and I just got us on to Rails 5.0, should be 5.1 by EOM.  We're currently on Ruby 2.4 so we did have to monkey patch a bit to get Lookbook working but it was fairly minor. We'll probably be on 2.5 by the end of the month and 2.4 is EOL so I dont think it's worth adjusting but I'm happy to open a PR if you'd like. The changes are super minor and VC works on Rails 5.0+ which support Ruby 2.2+, so maybe? Your call.

Either way, as I identify opportunities or bugs I'll be sure to get them to you.  Keep up the awesome work! Can't wait to see the future of Lookbook!

**Comment by allmarkedup** [comment]
Hey @DRBragg, thanks for your message - always really good to hear that people are finding Lookbook useful so appreciate you reaching out.

I'd be happy to look over a PR if you want to put one together - version parity with VC would certainly be nice :-) I don't have much insight as to what it would take to get it to work and it's unlikely something I'll have time to focus on so any input would always be welcome.

And yes if you find any bugs or have any other suggestions for improvements or feature requests please do open some issues! Would love to make Lookbook work well for as many different situations and setups as possible and any feedback will really help with that.

**Comment by adrienpoly** [comment]
hey @allmarkedup, 

not related to your previous comment but as I repported a few issues in the thread I just wanted to thank you for the latest 0.7.x series. I have seen I think (not benchmarked) significant improvements:
1. navigation between components seems much faster
2. when a component crash in the past I often needed to restart my server and/or some components would disapear from the left navbar (never saw that again since 0.7.2)
3. having the rails error displayed is very helpful in dev

🚀
